stages:
  - build
  - test
  - create sourcecode documentation
  - deploy sourcecode documentation
  - upload
  - release

variables:
  SLFTP_CI_IMAGE: registry.gitlab.com/slftp/ci-images/ubuntu-lts

### build stage ###

.buildwin64: &buildwin64
  stage: build
  script:
    - make.bat slftp_64
  after_script:
    # rename executable
    - ren slftp.exe slftp_x64-%CI_COMMIT_SHORT_SHA%.exe
  artifacts:
    # name of the generated zipfile
    name: "slftp_x64-%CI_JOB_NAME%-%CI_COMMIT_REF_NAME%-%CI_COMMIT_SHA%"
    paths:
      # included file
      - slftp_x64-%CI_COMMIT_SHORT_SHA%.exe
  tags:
    - windows
    - delphi 64bit

buildwin64-release:
  <<: *buildwin64
  before_script:
    # delete .git dir to avoid patching in git rev
    - rmdir .git /s /q
  only:
    - tags

buildwin64-development:
  <<: *buildwin64
  except:
    - tags

.buildlinux64: &buildlinux64
  stage: build
  image: $SLFTP_CI_IMAGE
  script:
    - make slftp_64
  after_script:
    # rename executable
    - mv slftp slftp_x64-${CI_COMMIT_SHORT_SHA}
  artifacts:
    # name of the generated zipfile
    name: "slftp_x64-${CI_JOB_NAME}-${CI_COMMIT_REF_NAME}-${CI_COMMIT_SHA}"
    paths:
      # included file
      - slftp_x64-${CI_COMMIT_SHORT_SHA}
  tags:
    - docker

buildlinux64-release:
  <<: *buildlinux64
  before_script:
    # delete .git dir to avoid patching in git rev
    - rm -fr .git
  only:
    - tags

buildlinux64-development:
  <<: *buildlinux64
  except:
    - tags

### test stage ###

testwin64:
  stage: test
  when: on_success
  before_script:
    - move config\* tests
  script:
    - make.bat test_64
  artifacts:
    paths:
      - tests\dunitx-results.xml
    reports:
      junit: tests\dunitx-results.xml
  tags:
    - windows
    - delphi 64bit

testlinux64:
  stage: test
  image: $SLFTP_CI_IMAGE
  when: on_success
  before_script:
    - cp /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1 ./libcrypto.so
    - cp /usr/lib/x86_64-linux-gnu/libssl.so.1.1 ./libssl.so
    - mv config/* tests/
  script:
    - make test
  tags:
    - docker

### sourcecode documentation stage ###

src-docs:
  stage: create sourcecode documentation
  image: $SLFTP_CI_IMAGE
  only:
    - dev
  except:
    # not for tag creation as they could be older
    - tags
  when: on_success
  allow_failure: true
  artifacts:
    name: "${CI_JOB_NAME}-${CI_COMMIT_REF_NAME}-${CI_COMMIT_SHA}"
    when: on_success
    paths:
      - src-docs/
  before_script:
    - mkdir src-docs
  script:
    - pasdoc --format html --write-uses-list --output src-docs irccommands/*.pas *.pas slftp.lpr
  tags:
    - docker

pages:
  stage: deploy sourcecode documentation
  only:
    - dev
  except:
    # not for tag creation as they could be older
    - tags
  when: on_success
  artifacts:
    when: on_success
    paths:
      - public/
  script:
    - cp -r src-docs public
  tags:
    - linux

### package & release stage ###

upload-package-files:
  stage: upload
  rules:
    - if: $CI_COMMIT_TAG
  variables:
    PACKAGE_REGISTRY_URL: "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic"
  before_script:
    # save environment variables also for release stage
    # get current version
    - echo "VERSION=$(awk '/SL_VERSION:/{print $NF}' slftp.inc | grep -oP '\d\.\d\.\d\w?\d?')" >> build.env
    # package number must be \d.\d.\d
    - echo "NUMBERVERSION=$(awk '/SL_VERSION:/{print $NF}' slftp.inc | grep -oP '\d\.\d\.\d')" >> build.env
    # load env variables before using them
    - source build.env
    # repo url
    - echo "PACKAGE_URL=${PACKAGE_REGISTRY_URL}/slftp_${VERSION}/${NUMBERVERSION}" >> build.env
    # naming convention for files
    - echo "WINDOWS_x64_BINARY=slftp-${VERSION}_x64.exe" >> build.env
    - echo "LINUX_x64_BINARY=slftp-${VERSION}_x64" >> build.env
    - echo "SLCONFIG=slftp-${VERSION}_config.zip" >> build.env
    - echo "SLDOCU=slftp-${VERSION}_documentation.zip" >> build.env
    - echo "SLHELPFILES=slftp-${VERSION}_helpfiles.zip" >> build.env
    - echo "SLPACKAGE=slFtp.${VERSION}.Linux.Windows.incl.Sources-SLDev.zip" >> build.env
    # usually this will only be executed if a tag is commited. but for developing/testing this script, it's nice to 
    # have this workingwithout a CI_COMMIT_TAG being set. therefore check if we have a CI_COMMIT_TAG, else use 
    # CI_COMMIT_BRANCH instead. this is used to download the source code and add it to the complete release package
    - |
      if [[ -n "${CI_COMMIT_TAG}" ]]
      then
        echo "SLBRANCHORTAG=${CI_COMMIT_TAG}" >> build.env
      else
        echo "SLBRANCHORTAG=${CI_COMMIT_BRANCH}" >> build.env
      fi
    # load env variables again
    - source build.env
  script:
    # remove git short hash from filename
    - mv slftp_x64-${CI_COMMIT_SHORT_SHA}.exe slftp_x64.exe
    - mv slftp_x64-${CI_COMMIT_SHORT_SHA} slftp_x64
    # upload windows versions
    - |
      curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file slftp_x64.exe ${PACKAGE_URL}/${WINDOWS_x64_BINARY}
    # upload linux versions
    - |
      curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file slftp_x64 ${PACKAGE_URL}/${LINUX_x64_BINARY}
    # create config, docs and helpfiles
    - |
      zip -r ${SLCONFIG} config
      zip -r ${SLDOCU} docs
      zip -r ${SLHELPFILES} helpfiles
    # upload config, docs and helpfiles
    - |
      curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file ${SLCONFIG} ${PACKAGE_URL}/${SLCONFIG}
      curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file ${SLDOCU} ${PACKAGE_URL}/${SLDOCU}
      curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file ${SLHELPFILES} ${PACKAGE_URL}/${SLHELPFILES}

     # create complete pack ready to run
    - |
     mkdir dist
     mkdir dist/help
     mkdir sources
     cp slftp_x64.exe dist
     cp slftp_x64 dist
     cp config/* dist
     cp helpfiles/* dist/help
    - |
     git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.com/slftp/slftp.git -b ${SLBRANCHORTAG} sources
    #delete the .git directory to save space
    - |
     rm -rf sources/.git
    - |
     curl -s https://cdn.mysql.com/archives/mysql-connector-c/mysql-connector-c-6.1.11-winx64.zip -o mysqlwin64.zip
    - |
     unzip -p mysqlwin64.zip */lib/libmysql.dll > dist/libmysql.dll
    - |
     rm -f mysqlwin64.zip
    - |
     wget https://downloads.mariadb.org/f/mariadb-10.5.9/winx64-packages/mariadb-10.5.9-winx64.zip?serve -O mariadbwin64.zip
    - |
     unzip -p mariadbwin64.zip */lib/libmariadb.dll > dist/libmariadb.dll
    - |
     rm -f mariadbwin64.zip
    - |
     curl -s https://www.sqlite.org/2021/sqlite-dll-win64-x64-3350400.zip -o sqlitewin64.zip
    - |
     unzip -p sqlitewin64.zip sqlite3.dll > dist/sqlite3-64.dll
    - |
     rm -f sqlitewin64.zip
    - |
     curl -s http://wiki.overbyte.eu/arch/openssl-1.1.1k-win64.zip -o opensslwin64.zip
    - |
     unzip -p opensslwin64.zip libcrypto-1_1-x64.dll > dist/libcrypto-1_1-x64.dll
    - |
     unzip -p opensslwin64.zip libssl-1_1-x64.dll > dist/libssl-1_1-x64.dll
    - |
     rm -f opensslwin64.zip
    - |
     zip -r ${SLPACKAGE} dist docs sources CHANGELOG
    # upload the pack
    - |
     curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file ${SLPACKAGE} ${PACKAGE_URL}/${SLPACKAGE}
  artifacts:
    reports:
      # publish environment variables
      dotenv: build.env
  tags:
    - linux

release:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  variables:
    # do not fetch the git repository
    GIT_STRATEGY: none
  needs:
    # get environment variables
    - job: upload-package-files
      artifacts: true
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - >
      release-cli create --name "slFtp ${CI_COMMIT_TAG}" --tag-name ${CI_COMMIT_TAG}
      --assets-link "{\"name\":\"${WINDOWS_x64_BINARY}\",\"url\":\"${PACKAGE_URL}/${WINDOWS_x64_BINARY}\"}"
      --assets-link "{\"name\":\"${LINUX_x64_BINARY}\",\"url\":\"${PACKAGE_URL}/${LINUX_x64_BINARY}\"}"
      --assets-link "{\"name\":\"${SLCONFIG}\",\"url\":\"${PACKAGE_URL}/${SLCONFIG}\"}"
      --assets-link "{\"name\":\"${SLDOCU}\",\"url\":\"${PACKAGE_URL}/${SLDOCU}\"}"
      --assets-link "{\"name\":\"${SLHELPFILES}\",\"url\":\"${PACKAGE_URL}/${SLHELPFILES}\"}"
      --assets-link "{\"name\":\"${SLPACKAGE}\",\"url\":\"${PACKAGE_URL}/${SLPACKAGE}\"}"
  tags:
    - docker
