{ Rule Descriptions for MVID => TMVIDRelease }
const
  MVIDGenreDescription: string = 'Returns the Genre parsed from nfo.';

  MVIDFilesDescription: string = 'Returns the number of files parsed from sfv. Returns -1 if NFO lookup is not yet ready.';

  MVIDYearDescription: string = 'Returns with the year of the MVID release date. Returns zero if NFO lookup is not yet ready.';

  MVIDVADescription: string = 'Returns true if release is Various Artists (VA). Returns false if NFO lookup is not yet ready.';

  MVIDPALDescription: string = 'Returns with the a boolean for PAL region. Returns false if NFO lookup is not yet ready.';

  MVIDNTSCDescription: string = 'Returns with the a boolean for NTSC region. Returns false if NFO lookup is not yet ready.';

  MVIDLIVEDescription: string = 'Returns with the a boolean for LIVE type. Returns false if NFO lookup is not yet ready.';

  MVIDLanguageDescription: string = 'Returns the Language parsed from nfo.';
